#!/bin/sh

KUNGFU_HOME_DIR=/opt/kungfu

KUNGFU_DATA_DIR=/shared/kungfu
KUNGFU_SOCKETS_DIR=$KUNGFU_DATA_DIR/socket
KUNGFU_LOGGING_DIR=$KUNGFU_DATA_DIR/log
KUNGFU_PID_DIR=$KUNGFU_DATA_DIR/pid
KUNGFU_RUNTIME_DIR=$KUNGFU_DATA_DIR/runtime
KUNGFU_JOURNAL_DIR=$KUNGFU_DATA_DIR/journal

groupadd -f --system --gid 666 bruce
useradd -p `openssl passwd -1 master` -m -d $KUNGFU_HOME_DIR --system --uid 666 -g bruce -G bruce,wheel --shell=/bin/bash bruce

cat <<EOT > $KUNGFU_HOME_DIR/.bashrc
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
EOT
chown -R bruce:bruce $KUNGFU_HOME_DIR

mkdir -p $KUNGFU_SOCKETS_DIR

mkdir -p $KUNGFU_LOGGING_DIR
mkdir -p $KUNGFU_LOGGING_DIR/supervisor
mkdir -p $KUNGFU_LOGGING_DIR/wingchun
mkdir -p $KUNGFU_LOGGING_DIR/strategy

mkdir -p $KUNGFU_PID_DIR

mkdir -p $KUNGFU_RUNTIME_DIR

mkdir -p $KUNGFU_JOURNAL_DIR
mkdir -p $KUNGFU_JOURNAL_DIR/system
mkdir -p $KUNGFU_JOURNAL_DIR/strategy
mkdir -p $KUNGFU_JOURNAL_DIR/user

mkdir -p $KUNGFU_JOURNAL_DIR/MD/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/CTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/CTP

mkdir -p $KUNGFU_JOURNAL_DIR/MD/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/XTP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/XTP

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BINANCE

mkdir -p $KUNGFU_JOURNAL_DIR/MD/INDODAX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/INDODAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/INDODAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/INDODAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/INDODAX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/INDODAX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OKEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/COINMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/COINMEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCK

mkdir -p $KUNGFU_JOURNAL_DIR/MD/ASCENDEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/ASCENDEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/ASCENDEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/ASCENDEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/ASCENDEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/ASCENDEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITFINEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITFINEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITMEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/HITBTC
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/HITBTC

mkdir -p $KUNGFU_JOURNAL_DIR/MD/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OCEANEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OCEANEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/HUOBI
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/HUOBI

mkdir -p $KUNGFU_JOURNAL_DIR/MD/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OCEANEXB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OCEANEXB

mkdir -p $KUNGFU_JOURNAL_DIR/MD/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/PROBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/PROBIT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITHUMB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITHUMB

mkdir -p $KUNGFU_JOURNAL_DIR/MD/UPBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/UPBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/UPBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/UPBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/UPBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/UPBIT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/DAYBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/DAYBIT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/KUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/KUCOIN

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITFLYER
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITFLYER
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITFLYER
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITFLYER
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITFLYER
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITFLYER

mkdir -p $KUNGFU_JOURNAL_DIR/MD/KRAKEN
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/KRAKEN
mkdir -p $KUNGFU_JOURNAL_DIR/TD/KRAKEN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/KRAKEN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/KRAKEN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/KRAKEN

mkdir -p $KUNGFU_JOURNAL_DIR/MD/IB
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/IB
mkdir -p $KUNGFU_JOURNAL_DIR/TD/IB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/IB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/IB
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/IB

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITTREX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITTREX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITTREX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITTREX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITTREX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITTREX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/POLONIEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/POLONIEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/POLONIEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/POLONIEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/POLONIEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/POLONIEX


mkdir -p $KUNGFU_JOURNAL_DIR/MD/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BITSTAMP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BITSTAMP


mkdir -p $KUNGFU_JOURNAL_DIR/MD/DERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/DERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/DERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/DERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/DERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/DERIBIT


mkdir -p $KUNGFU_JOURNAL_DIR/MD/EMX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/EMX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/EMX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/EMX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/EMX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/EMX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/COINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/COINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/COINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/COINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/COINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/COINFLEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/COINFLOOR
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/COINFLOOR
mkdir -p $KUNGFU_JOURNAL_DIR/TD/COINFLOOR
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/COINFLOOR
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/COINFLOOR
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/COINFLOOR

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCKKUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCKKUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCKKUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCKKUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCKKUCOIN
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCKKUCOIN

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCKBITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCKBITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCKBITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCKBITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCKBITMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCKBITMEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BINANCEF
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BINANCEF
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BINANCEF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BINANCEF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BINANCEF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BINANCEF

mkdir -p $KUNGFU_JOURNAL_DIR/MD/HBDM
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/HBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD/HBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/HBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/HBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/HBDM

mkdir -p $KUNGFU_JOURNAL_DIR/MD/KUMEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/KUMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/KUMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/KUMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/KUMEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/KUMEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/ERISX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/ERISX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/ERISX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/ERISX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/ERISX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/ERISX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BEQUANT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BEQUANT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BEQUANT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BEQUANT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BEQUANT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BEQUANT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/KRAKENF
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/KRAKENF
mkdir -p $KUNGFU_JOURNAL_DIR/TD/KRAKENF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/KRAKENF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/KRAKENF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/KRAKENF

mkdir -p $KUNGFU_JOURNAL_DIR/MD/COINCHECK
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/COINCHECK
mkdir -p $KUNGFU_JOURNAL_DIR/TD/COINCHECK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/COINCHECK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/COINCHECK
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/COINCHECK


mkdir -p $KUNGFU_JOURNAL_DIR/MD/OKEXF
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OKEXF
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OKEXF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OKEXF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OKEXF
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OKEXF

mkdir -p $KUNGFU_JOURNAL_DIR/MD/FTX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/FTX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/FTX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/FTX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/FTX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/FTX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCKHBDM
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCKHBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCKHBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCKHBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCKHBDM
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCKHBDM

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCKBINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCKBINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCKBINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCKBINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCKBINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCKBINANCE

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCKCOINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCKCOINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCKCOINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCKCOINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCKCOINFLEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCKCOINFLEX

mkdir -p $KUNGFU_JOURNAL_DIR/MD/MOCKDERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/MOCKDERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD/MOCKDERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/MOCKDERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/MOCKDERIBIT
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/MOCKDERIBIT

mkdir -p $KUNGFU_JOURNAL_DIR/MD/GOOGLETRENDS
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/GOOGLETRENDS
mkdir -p $KUNGFU_JOURNAL_DIR/TD/GOOGLETRENDS
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/GOOGLETRENDS
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/GOOGLETRENDS
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/GOOGLETRENDS

mkdir -p $KUNGFU_JOURNAL_DIR/MD/QDP
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/QDP
mkdir -p $KUNGFU_JOURNAL_DIR/TD/QDP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/QDP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/QDP
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/QDP

mkdir -p $KUNGFU_JOURNAL_DIR/MD/BINANCED
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BINANCED
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BINANCED
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BINANCED
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BINANCED
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BINANCED

chown -R bruce:bruce $KUNGFU_DATA_DIR

chmod +x /opt/kungfu/master/bin/*
ln -sf /opt/kungfu/master/bin/yjj /usr/bin/yjj
ln -sf /opt/kungfu/master/bin/wingchun /usr/bin/wingchun
ln -sf /opt/kungfu/master/bin/kungfuctl /usr/bin/kungfuctl

cat <<EOT > /usr/lib64/python2.7/site-packages/kungfu.pth
/opt/kungfu/master/lib/python2.7/site-packages
EOT

ln -sf /opt/kungfu/master/etc/systemd/user/kungfu.service /etc/systemd/system/kungfu.service

systemctl daemon-reload
systemctl start kungfu

