// auto generated by struct_info_parser.py, please DO NOT edit!!!

#ifndef LONGFIST_UTILS_H
#define LONGFIST_UTILS_H

#include "LFDataStruct.h"
#include "LFConstants.h"
#include <string>
#include <algorithm>
#include <cctype>
inline std::string getExchangeName(int exchange_id)
{
	switch(exchange_id)
	{
		case EXCHANGE_ID_SZE: // 深圳证券交易所
			return EXCHANGE_SZE;
		case EXCHANGE_ID_CFFEX: // 中国金融期货交易所
			return EXCHANGE_CFFEX;
		case EXCHANGE_ID_SSE: // 上海证券交易所
			return EXCHANGE_SSE;
		case EXCHANGE_ID_DCE: // 大连商品交易所
			return EXCHANGE_DCE;
		case EXCHANGE_ID_SHFE: // 上海期货交易所
			return EXCHANGE_SHFE;
		case EXCHANGE_ID_CZCE: // 郑州商品交易所
			return EXCHANGE_CZCE;
		case EXCHANGE_ID_BINANCE:
			return EXCHANGE_BINANCE;
		case EXCHANGE_ID_INDODAX:
			return EXCHANGE_INDODAX;
		case EXCHANGE_ID_OKEX:
			return EXCHANGE_OKEX;
		case EXCHANGE_ID_COINMEX:
			return EXCHANGE_COINMEX;
		case EXCHANGE_ID_MOCK:
			return EXCHANGE_MOCK;
		case EXCHANGE_ID_ASCENDEX:
			return EXCHANGE_ASCENDEX;
		case EXCHANGE_ID_BITFINEX:
			return EXCHANGE_BITFINEX;
		case EXCHANGE_ID_BITMEX:
			return EXCHANGE_BITMEX;
		case EXCHANGE_ID_HITBTC:
			return EXCHANGE_HITBTC;
		case EXCHANGE_ID_OCEANEX:
			return EXCHANGE_OCEANEX;
		case EXCHANGE_ID_HUOBI:
			return EXCHANGE_HUOBI;
		case EXCHANGE_ID_OCEANEXB:
			return EXCHANGE_OCEANEXB;
		case EXCHANGE_ID_PROBIT:
			return EXCHANGE_PROBIT;
		case EXCHANGE_ID_BITHUMB:
			return EXCHANGE_BITHUMB;
		case EXCHANGE_ID_UPBIT:
			return EXCHANGE_UPBIT;
		case EXCHANGE_ID_DAYBIT:
			return EXCHANGE_DAYBIT;
		case EXCHANGE_ID_KUCOIN:
			return EXCHANGE_KUCOIN;
		case EXCHANGE_ID_BITFLYER:
			return EXCHANGE_BITFLYER;
		case EXCHANGE_ID_KRAKEN:
			return EXCHANGE_KRAKEN;
		case EXCHANGE_ID_IB:
			return EXCHANGE_IB;
		case EXCHANGE_ID_BITTREX:
			return EXCHANGE_BITTREX;
		case EXCHANGE_ID_POLONIEX:
			return EXCHANGE_POLONIEX;
		case EXCHANGE_ID_BITSTAMP:
			return EXCHANGE_BITSTAMP;
		case EXCHANGE_ID_DERIBIT:
			return EXCHANGE_DERIBIT;
		case EXCHANGE_ID_EMX:
			return EXCHANGE_EMX;
		case EXCHANGE_ID_COINFLEX:
			return EXCHANGE_COINFLEX;
		case EXCHANGE_ID_COINFLOOR:
			return EXCHANGE_COINFLOOR;
		case EXCHANGE_ID_MOCKKUCOIN:
			return EXCHANGE_MOCKKUCOIN;
		case EXCHANGE_ID_MOCKBITMEX:
			return EXCHANGE_MOCKBITMEX;
		case EXCHANGE_ID_BINANCEF:
			return EXCHANGE_BINANCEF;
		case EXCHANGE_ID_HBDM:
			return EXCHANGE_HBDM;
		case EXCHANGE_ID_KUMEX:
			return EXCHANGE_KUMEX;
		case EXCHANGE_ID_ERISX:
			return EXCHANGE_ERISX;
		case EXCHANGE_ID_BEQUANT:
			return EXCHANGE_BEQUANT;
		case EXCHANGE_ID_KRAKENF:
			return EXCHANGE_KRAKENF;
		case EXCHANGE_ID_COINCHECK:
			return EXCHANGE_COINCHECK;
		case EXCHANGE_ID_OKEXF:
			return EXCHANGE_OKEXF;
		case EXCHANGE_ID_FTX:
			return EXCHANGE_FTX;
		case EXCHANGE_ID_GOOGLETRENDS:
			return EXCHANGE_GOOGLETRENDS;
		case EXCHANGE_ID_QDP:
			return EXCHANGE_QDP;
		case EXCHANGE_ID_BINANCED:
			return EXCHANGE_BINANCED;
		default:
			return "";
	}
}

inline int getExchangeId(std::string exchange_name)
{
	std::transform(exchange_name.begin(),exchange_name.end(),exchange_name.begin(),::toupper);
	if (exchange_name.compare(EXCHANGE_SZE) == 0) //深圳证券交易所
		return EXCHANGE_ID_SZE;
	else if (exchange_name.compare(EXCHANGE_CFFEX) == 0) //中国金融期货交易所
		return EXCHANGE_ID_CFFEX;
	else if (exchange_name.compare(EXCHANGE_SSE) == 0) //上海证券交易所
		return EXCHANGE_ID_SSE;
	else if (exchange_name.compare(EXCHANGE_DCE) == 0) //大连商品交易所
		return EXCHANGE_ID_DCE;
	else if (exchange_name.compare(EXCHANGE_SHFE) == 0) //上海期货交易所
		return EXCHANGE_ID_SHFE;
	else if (exchange_name.compare(EXCHANGE_CZCE) == 0) //郑州商品交易所
		return EXCHANGE_ID_CZCE;
	else if (exchange_name.compare(EXCHANGE_BINANCE) == 0) 
		return EXCHANGE_ID_BINANCE;
	else if (exchange_name.compare(EXCHANGE_INDODAX) == 0) 
		return EXCHANGE_ID_INDODAX;
	else if (exchange_name.compare(EXCHANGE_OKEX) == 0) 
		return EXCHANGE_ID_OKEX;
	else if (exchange_name.compare(EXCHANGE_COINMEX) == 0) 
		return EXCHANGE_ID_COINMEX;
	else if (exchange_name.compare(EXCHANGE_MOCK) == 0) 
		return EXCHANGE_ID_MOCK;
	else if (exchange_name.compare(EXCHANGE_ASCENDEX) == 0) 
		return EXCHANGE_ID_ASCENDEX;
	else if (exchange_name.compare(EXCHANGE_BITFINEX) == 0) 
		return EXCHANGE_ID_BITFINEX;
	else if (exchange_name.compare(EXCHANGE_BITMEX) == 0) 
		return EXCHANGE_ID_BITMEX;
	else if (exchange_name.compare(EXCHANGE_HITBTC) == 0) 
		return EXCHANGE_ID_HITBTC;
	else if (exchange_name.compare(EXCHANGE_OCEANEX) == 0) 
		return EXCHANGE_ID_OCEANEX;
	else if (exchange_name.compare(EXCHANGE_HUOBI) == 0) 
		return EXCHANGE_ID_HUOBI;
	else if (exchange_name.compare(EXCHANGE_OCEANEXB) == 0) 
		return EXCHANGE_ID_OCEANEXB;
	else if (exchange_name.compare(EXCHANGE_PROBIT) == 0) 
		return EXCHANGE_ID_PROBIT;
	else if (exchange_name.compare(EXCHANGE_BITHUMB) == 0) 
		return EXCHANGE_ID_BITHUMB;
	else if (exchange_name.compare(EXCHANGE_UPBIT) == 0) 
		return EXCHANGE_ID_UPBIT;
	else if (exchange_name.compare(EXCHANGE_DAYBIT) == 0) 
		return EXCHANGE_ID_DAYBIT;
	else if (exchange_name.compare(EXCHANGE_KUCOIN) == 0) 
		return EXCHANGE_ID_KUCOIN;
	else if (exchange_name.compare(EXCHANGE_BITFLYER) == 0) 
		return EXCHANGE_ID_BITFLYER;
	else if (exchange_name.compare(EXCHANGE_KRAKEN) == 0) 
		return EXCHANGE_ID_KRAKEN;
	else if (exchange_name.compare(EXCHANGE_IB) == 0) 
		return EXCHANGE_ID_IB;
	else if (exchange_name.compare(EXCHANGE_BITTREX) == 0) 
		return EXCHANGE_ID_BITTREX;
	else if (exchange_name.compare(EXCHANGE_POLONIEX) == 0) 
		return EXCHANGE_ID_POLONIEX;
	else if (exchange_name.compare(EXCHANGE_BITSTAMP) == 0) 
		return EXCHANGE_ID_BITSTAMP;
	else if (exchange_name.compare(EXCHANGE_DERIBIT) == 0) 
		return EXCHANGE_ID_DERIBIT;
	else if (exchange_name.compare(EXCHANGE_EMX) == 0) 
		return EXCHANGE_ID_EMX;
	else if (exchange_name.compare(EXCHANGE_COINFLEX) == 0) 
		return EXCHANGE_ID_COINFLEX;
	else if (exchange_name.compare(EXCHANGE_COINFLOOR) == 0) 
		return EXCHANGE_ID_COINFLOOR;
	else if (exchange_name.compare(EXCHANGE_MOCKKUCOIN) == 0) 
		return EXCHANGE_ID_MOCKKUCOIN;
	else if (exchange_name.compare(EXCHANGE_MOCKBITMEX) == 0) 
		return EXCHANGE_ID_MOCKBITMEX;
	else if (exchange_name.compare(EXCHANGE_BINANCEF) == 0) 
		return EXCHANGE_ID_BINANCEF;
	else if (exchange_name.compare(EXCHANGE_HBDM) == 0)
		return EXCHANGE_ID_HBDM;
	else if (exchange_name.compare(EXCHANGE_KUMEX) == 0) 
		return EXCHANGE_ID_KUMEX;
	else if (exchange_name.compare(EXCHANGE_ERISX) == 0) 
		return EXCHANGE_ID_ERISX;
	else if (exchange_name.compare(EXCHANGE_BEQUANT)==0)
		return EXCHANGE_ID_BEQUANT;
	else if (exchange_name.compare(EXCHANGE_KRAKENF)==0)
		return EXCHANGE_ID_KRAKENF;
	else if (exchange_name.compare(EXCHANGE_COINCHECK) == 0) 
		return EXCHANGE_ID_COINCHECK;
	else if (exchange_name.compare(EXCHANGE_OKEXF) == 0) 
		return EXCHANGE_ID_OKEXF;
	else if (exchange_name.compare(EXCHANGE_FTX) == 0) 
		return EXCHANGE_ID_FTX;
	else if (exchange_name.compare(EXCHANGE_GOOGLETRENDS) == 0)
		return EXCHANGE_ID_GOOGLETRENDS;
	else if (exchange_name.compare(EXCHANGE_QDP) == 0)
		return EXCHANGE_ID_QDP;
	else if (exchange_name.compare(EXCHANGE_BINANCED) == 0)
		return EXCHANGE_ID_BINANCED;
	else
	{
		return -1;
	}
	
}

typedef std::pair<std::string, std::string> JournalPair;

inline JournalPair getJournalPair(const std::string& journal_type,int source)
{
	std::string  strSource = get_str_from_source_index(source);
	if(strSource != "unknown")
	{
		std::transform(strSource.begin(),strSource.end(),strSource.begin(),[](unsigned char c) -> unsigned char { return std::toupper(c); });
		return {"/shared/kungfu/journal/"+journal_type+"/"+strSource+"/", journal_type+"_"+strSource};
	}
	else
	{
		return {"", ""};
	}
	
}

inline JournalPair getMdJournalPair(int source)
{
	return getJournalPair("MD",source);
	/* 
	switch(source)
	{
		case 1:
			return {"/shared/kungfu/journal/MD/CTP/", "MD_CTP"};
		case 15:
			return {"/shared/kungfu/journal/MD/XTP/", "MD_XTP"};
		case 16:
			return {"/shared/kungfu/journal/MD/BINANCE/", "MD_BINANCE"};
		case 18:
			return {"/shared/kungfu/journal/MD/OKEX/", "MD_OKEX"};
		case 19:
			return {"/shared/kungfu/journal/MD/COINMEX/", "MD_COINMEX"};
		case 20:
			return {"/shared/kungfu/journal/MD/MOCK/", "MD_MOCK"};
		case 21:
			return {"/shared/kungfu/journal/MD/ASCENDEX/", "MD_ASCENDEX"};
		case 22:
			return {"/shared/kungfu/journal/MD/BITFINEX/", "MD_BITFINEX"};
		case 23:
			return {"/shared/kungfu/journal/MD/BITMEX/", "MD_BITMEX"};
		case 24:
			return {"/shared/kungfu/journal/MD/HITBTC/", "MD_HITBTC"};
		case 25:
			return {"/shared/kungfu/journal/MD/OCEANEX/", "MD_OCEANEX"};
		case 26:
			return {"/shared/kungfu/journal/MD/HUOBI/", "MD_HUOBI"};
		case 28:
			return{ "/shared/kungfu/journal/MD/PROBIT/", "MD_PROBIT" };
		case 29:
			return { "/shared/kungfu/journal/MD/BITHUMB/", "MD_BITHUMB" };
		default:
			return {"", ""};
	}
	*/
}

inline JournalPair getMdRawJournalPair(int source)
{
	return getJournalPair("MD_RAW",source);
	/* 
	switch(source)
	{
		case 1:
			return {"/shared/kungfu/journal/MD_RAW/CTP/", "MDRAW_CTP"};
		case 15:
			return {"/shared/kungfu/journal/MD_RAW/XTP/", "MDRAW_XTP"};
		case 19:
			return {"/shared/kungfu/journal/MD_RAW/COINMEX/", "MDRAW_COINMEX"};
		case 20:
			return {"/shared/kungfu/journal/MD_RAW/MOCK/", "MDRAW_MOCK"};
		case 21:
			return {"/shared/kungfu/journal/MD_RAW/ASCENDEX/", "MDRAW_ASCENDEX"};
		case 22:
			return {"/shared/kungfu/journal/MD_RAW/BITFINEX/", "MDRAW_BITFINEX"};
        case 23:
            return {"/shared/kungfu/journal/MD_RAW/BITMEX/", "MDRAW_BITMEX"};
		case 24:
			return {"/shared/kungfu/journal/MD_RAW/HITBTC/", "MDRAW_HITBTC"};
		case 25:
			return {"/shared/kungfu/journal/MD_RAW/OCEANEX/", "MDRAW_OCEANEX"};
        case 26:
            return {"/shared/kungfu/journal/MD_RAW/HUOBI/", "MDRAW_HUOBI"};
		case 28:
			return{ "/shared/kungfu/journal/MD_RAW/PROBIT/", "MDRAW_PROBIT" };
		case 29:
            return{ "/shared/kungfu/journal/MD_RAW/BITHUMB/", "MDRAW_BITHUMB" };
		case 30:
            return{ "/shared/kungfu/journal/MD_RAW/UPBIT/", "MDRAW_UPBIT" };
		case 31:
            return{ "/shared/kungfu/journal/MD_RAW/DAYBIT/", "MDRAW_DAYBIT" };
		case 32:
            return{ "/shared/kungfu/journal/MD_RAW/KUCOIN/", "MDRAW_KUCOIN" };
		case 33:
            return{ "/shared/kungfu/journal/MD_RAW/BITFLYER/", "MDRAW_BITFLYER" };
		case 34:
            return{ "/shared/kungfu/journal/MD_RAW/KRAKEN/", "MDRAW_KRAKEN" };
		case 35:
            return{ "/shared/kungfu/journal/MD_RAW/IB/", "MDRAW_IB" };
		case 36:
            return{ "/shared/kungfu/journal/MD_RAW/BITTREX/", "MDRAW_BITTREX" };
		case 37:
            return{ "/shared/kungfu/journal/MD_RAW/POLONIEX/", "MDRAW_POLONIEX" };
		case 38:
            return{ "/shared/kungfu/journal/MD_RAW/BITSTAMP/", "MDRAW_BITSTAMP" };
		case 39:
            return{ "/shared/kungfu/journal/MD_RAW/DERIBIT/", "MDRAW_DERIBIT" };
		case 40:
            return{ "/shared/kungfu/journal/MD_RAW/EMX/", "MDRAW_EMX" };
        case 41:
            return{ "/shared/kungfu/journal/MD_RAW/COINFLEX/", "MDRAW_COINFLEX" };
         case 42:
            return{ "/shared/kungfu/journal/MD_RAW/COINFLOOR/", "MDRAW_COINFLOOR" };
		default:
			return {"", ""};
	}
	*/
}

inline JournalPair getTdJournalPair(int source)
{
	return getJournalPair("TD",source);
	/* 
	switch(source)
	{
		case 1:
			return {"/shared/kungfu/journal/TD/CTP/", "TD_CTP"};
		case 15:
			return {"/shared/kungfu/journal/TD/XTP/", "TD_XTP"};
		case 16:
			return {"/shared/kungfu/journal/TD/BINANCE/", "TD_BINANCE"};
		case 18:
			return {"/shared/kungfu/journal/TD/OKEX/", "TD_OKEX"};	
		case 19:
			return {"/shared/kungfu/journal/TD/COINMEX/", "TD_COINMEX"};
		case 20:
			return {"/shared/kungfu/journal/TD/MOCK/", "TD_MOCK"};
		case 21:
			return {"/shared/kungfu/journal/TD/ASCENDEX/", "TD_ASCENDEX"};
		case 22:
			return {"/shared/kungfu/journal/TD/BITFINEX/", "TD_BITFINEX"};
        case 23:
            return {"/shared/kungfu/journal/TD/BITMEX/", "TD_BITMEX"};
		case 24:
			return {"/shared/kungfu/journal/TD/HITBTC/", "TD_HITBTC"};
		case 25:
			return {"/shared/kungfu/journal/TD/OCEANEX/", "TD_OCEANEX"};
		case 26:
			return {"/shared/kungfu/journal/TD/HUOBI/", "TD_HUOBI"};
		case 28:
			return {"/shared/kungfu/journal/TD/PROBIT/", "TD_PROBIT"};
		case 29:
            return {"/shared/kungfu/journal/TD/BITHUMB/", "TD_BITHUMB"};
		case 30:
            return {"/shared/kungfu/journal/TD/UPBIT/", "TD_UPBIT"};
		case 31:
            return {"/shared/kungfu/journal/TD/DAYBIT/", "TD_DAYBIT"};
		case 32:
            return {"/shared/kungfu/journal/TD/KUCOIN/", "TD_KUCOIN"};
		case 33:
            return {"/shared/kungfu/journal/TD/BITFLYER/", "TD_BITFLYER"};
		case 34:
            return {"/shared/kungfu/journal/TD/KRAKEN/", "TD_KRAKEN"};
		case 35:
            return {"/shared/kungfu/journal/TD/IB/", "TD_IB"};
		case 36:
            return {"/shared/kungfu/journal/TD/BITTREX/", "TD_BITTREX"};
		case 37:
            return {"/shared/kungfu/journal/TD/POLONIEX/", "TD_POLONIEX"};
		case 38:
            return {"/shared/kungfu/journal/TD/BITSTAMP/", "TD_BITSTAMP"};
		case 39:
            return {"/shared/kungfu/journal/TD/DERIBIT/", "TD_DERIBIT"};
		case 40:
            return {"/shared/kungfu/journal/TD/EMX/", "TD_EMX"};
        case 41:
            return {"/shared/kungfu/journal/TD/COINFLEX/", "TD_COINFLEX"};
        case 42:
            return {"/shared/kungfu/journal/TD/COINFLOOR/", "TD_COINFLOOR"};
		default:
			return {"", ""};
	}
	*/
}

inline JournalPair getTdSendJournalPair(int source)
{
	return getJournalPair("TD_SEND",source);
	/*
	switch(source)
	{
		case 1:
			return {"/shared/kungfu/journal/TD_SEND/CTP/", "TD_SEND_CTP"};
		case 15:
			return {"/shared/kungfu/journal/TD_SEND/XTP/", "TD_SEND_XTP"};
		case 16:
            return {"/shared/kungfu/journal/TD_SEND/BINANCE/", "TD_SEND_BINANCE"};
		case 18:
			return {"/shared/kungfu/journal/TD_SEND/OKEX/", "TD_SEND_OKEX"};
		case 19:
			return {"/shared/kungfu/journal/TD_SEND/COINMEX/", "TD_SEND_COINMEX"};
		case 20:
			return {"/shared/kungfu/journal/TD_SEND/MOCK/", "TD_SEND_MOCK"};
		case 21:
			return {"/shared/kungfu/journal/TD_SEND/ASCENDEX/", "TD_SEND_ASCENDEX"};
		case 22:
			return {"/shared/kungfu/journal/TD_SEND/BITFINEX/", "TD_SEND_BITFINEX"};
        case 23:
            return {"/shared/kungfu/journal/TD_SEND/BITMEX/", "TD_SEND_BITMEX"};
		case 24:
			return {"/shared/kungfu/journal/TD_SEND/HITBTC/", "TD_SEND_HITBTC"};
		case 25:
			return {"/shared/kungfu/journal/TD_SEND/OCEANEX/", "TD_SEND_OCEANEX"};
        case 26:
            return {"/shared/kungfu/journal/TD_SEND/HUOBI/", "TD_SEND_HUOBI"};
        case 28:
			return {"/shared/kungfu/journal/TD_SEND/PROBIT/", "TD_SEND_PROBIT"};
		case 29:
            return {"/shared/kungfu/journal/TD_SEND/BITHUMB/", "TD_SEND_BITHUMB"};
		case 30:
            return {"/shared/kungfu/journal/TD_SEND/UPBIT/", "TD_SEND_UPBIT"};
		case 31:
            return {"/shared/kungfu/journal/TD_SEND/DAYBIT/", "TD_SEND_DAYBIT"};
		case 32:
            return {"/shared/kungfu/journal/TD_SEND/KUCOIN/", "TD_SEND_KUCOIN"};
		case 33:
            return {"/shared/kungfu/journal/TD_SEND/BITFLYER/", "TD_SEND_BITFLYER"};
		case 34:
            return {"/shared/kungfu/journal/TD_SEND/KRAKEN/", "TD_SEND_KRAKEN"};
		case 35:
            return {"/shared/kungfu/journal/TD_SEND/IB/", "TD_SEND_IB"};
		case 36:
            return {"/shared/kungfu/journal/TD_SEND/BITTREX/", "TD_SEND_BITTREX"};
		case 37:
            return {"/shared/kungfu/journal/TD_SEND/POLONIEX/", "TD_SEND_POLONIEX"};
		case 38:
            return {"/shared/kungfu/journal/TD_SEND/BITSTAMP/", "TD_SEND_BITSTAMP"};
		case 39:
            return {"/shared/kungfu/journal/TD_SEND/DERIBIT/", "TD_SEND_DERIBIT"};
		case 40:
            return {"/shared/kungfu/journal/TD_SEND/EMX/", "TD_SEND_EMX"};
        case 41:
            return {"/shared/kungfu/journal/TD_SEND/COINFLEX/", "TD_SEND_COINFLEX"};
         case 42:
            return {"/shared/kungfu/journal/TD_SEND/COINFLOOR/", "TD_SEND_COINFLOOR"};
		default:
			return {"", ""};
	}
	*/
}

inline JournalPair getTdRawJournalPair(int source)
{
	return getJournalPair("TD_RAW",source);
	/* 
	switch(source)
	{
		case 1:
			return {"/shared/kungfu/journal/TD_RAW/CTP/", "TD_RAW_CTP"};
		case 15:
			return {"/shared/kungfu/journal/TD_RAW/XTP/", "TD_RAW_XTP"};
		case 16:
			return {"/shared/kungfu/journal/TD_RAW/BINANCE/", "TD_RAW_BINANCE"};
		case 18:
			return {"/shared/kungfu/journal/TD_RAW/OKEX/", "TD_RAW_OKEX"};	
		case 19:
			return {"/shared/kungfu/journal/TD_RAW/COINMEX/", "TD_RAW_COINMEX"};
		case 20:
			return {"/shared/kungfu/journal/TD_RAW/MOCK/", "TD_RAW_MOCK"};
		case 21:
			return {"/shared/kungfu/journal/TD_RAW/ASCENDEX/", "TD_RAW_ASCENDEX"};
		case 22:
			return {"/shared/kungfu/journal/TD_RAW/BITFINEX/", "TD_RAW_BITFINEX"};
        case 23:
            return {"/shared/kungfu/journal/TD_RAW/BITMEX/", "TD_RAW_BITMEX"};
		case 24:
			return {"/shared/kungfu/journal/TD_RAW/HITBTC/", "TD_RAW_HITBTC"};
		case 25:
			return {"/shared/kungfu/journal/TD_RAW/OCEANEX/", "TD_RAW_OCEANEX"};
        case 26:
            return {"/shared/kungfu/journal/TD_RAW/HUOBI/", "TD_RAW_HUOBI"};
        case 28:
			return {"/shared/kungfu/journal/TD_RAW/PROBIT/", "TD_RAW_PROBIT"};
		case 29:
            return {"/shared/kungfu/journal/TD_RAW/BITHUMB/", "TD_RAW_BITHUMB"};
		case 30:
            return {"/shared/kungfu/journal/TD_RAW/UPBIT/", "TD_RAW_UPBIT"};
		case 31:
            return {"/shared/kungfu/journal/TD_RAW/DAYBIT/", "TD_RAW_DAYBIT"};
		case 32:
            return {"/shared/kungfu/journal/TD_RAW/KUCOIN/", "TD_RAW_KUCOIN"};
		case 33:
            return {"/shared/kungfu/journal/TD_RAW/BITFLYER/", "TD_RAW_BITFLYER"};
		case 34:
            return {"/shared/kungfu/journal/TD_RAW/KRAKEN/", "TD_RAW_KRAKEN"};
		case 35:
            return {"/shared/kungfu/journal/TD_RAW/IB/", "TD_RAW_IB"};
		case 36:
            return {"/shared/kungfu/journal/TD_RAW/BITTREX/", "TD_RAW_BITTREX"};
		case 37:
            return {"/shared/kungfu/journal/TD_RAW/POLONIEX/", "TD_RAW_POLONIEX"};
		case 38:
            return {"/shared/kungfu/journal/TD_RAW/BITSTAMP/", "TD_RAW_BITSTAMP"};
		case 39:
            return {"/shared/kungfu/journal/TD_RAW/DERIBIT/", "TD_RAW_DERIBIT"};
		case 40:
            return {"/shared/kungfu/journal/TD_RAW/EMX/", "TD_RAW_EMX"};
        case 41:
            return {"/shared/kungfu/journal/TD_RAW/COINFLEX/", "TD_RAW_COINFLEX"};
        case 42:
            return {"/shared/kungfu/journal/TD_RAW/COINFLOOR/", "TD_RAW_COINFLOOR"};
		default:
			return {"", ""};
	}
	*/
}

inline JournalPair getTdQJournalPair(int source)
{
	return getJournalPair("TD_Q",source);
	/* 
	switch(source)
	{
		case 1:
			return {"/shared/kungfu/journal/TD_Q/CTP/", "TD_Q_CTP"};
		case 15:
			return {"/shared/kungfu/journal/TD_Q/XTP/", "TD_Q_XTP"};
		case 16:
			return {"/shared/kungfu/journal/TD_Q/BINANCE/", "TD_Q_BINANCE"};
		case 18:
			return {"/shared/kungfu/journal/TD_Q/OKEX/", "TD_Q_OKEX"};
		case 19:
			return {"/shared/kungfu/journal/TD_Q/COINMEX/", "TD_Q_COINMEX"};
		case 20:
			return {"/shared/kungfu/journal/TD_Q/MOCK/", "TD_Q_MOCK"};
		case 21:
			return {"/shared/kungfu/journal/TD_Q/ASCENDEX/", "TD_Q_ASCENDEX"};
		case 22:
			return {"/shared/kungfu/journal/TD_Q/BITFINEX/", "TD_Q_BITFINEX"};
        case 23:
            return {"/shared/kungfu/journal/TD_Q/BITMEX/", "TD_Q_BITMEX"};
		case 24:
			return {"/shared/kungfu/journal/TD_Q/HITBTC/", "TD_Q_HITBTC"};
		case 25:
			return {"/shared/kungfu/journal/TD_Q/OCEANEX/", "TD_Q_OCEANEX"};
        case 26:
            return {"/shared/kungfu/journal/TD_Q/HUOBI/", "TD_Q_HUOBI"};
        case 28:
			return {"/shared/kungfu/journal/TD_Q/PROBIT/", "TD_Q_PROBIT"};
		case 29:
            return {"/shared/kungfu/journal/TD_Q/BITHUMB/", "TD_Q_BITHUMB"};
		case 30:
			return {"/shared/kungfu/journal/TD_Q/UPBIT/", "TD_Q_UPBIT"};
		case 31:
			return {"/shared/kungfu/journal/TD_Q/DAYBIT/", "TD_Q_DAYBIT"};
		case 32:
			return {"/shared/kungfu/journal/TD_Q/KUCOIN/", "TD_Q_KUCOIN"};
		case 33:
			return {"/shared/kungfu/journal/TD_Q/BITFLYER/", "TD_Q_BITFLYER"};
		case 34:
			return {"/shared/kungfu/journal/TD_Q/KRAKEN/", "TD_Q_KRAKEN"};
		case 35:
			return {"/shared/kungfu/journal/TD_Q/IB/", "TD_Q_IB"};
		case 36:
			return {"/shared/kungfu/journal/TD_Q/BITTREX/", "TD_Q_BITTREX"};
		case 37:
			return {"/shared/kungfu/journal/TD_Q/POLONIEX/", "TD_Q_POLONIEX"};
		case 38:
			return {"/shared/kungfu/journal/TD_Q/BITSTAMP/", "TD_Q_BITSTAMP"};
		case 39:
			return {"/shared/kungfu/journal/TD_Q/DERIBIT/", "TD_Q_DERIBIT"};
		case 40:
			return {"/shared/kungfu/journal/TD_Q/EMX/", "TD_Q_EMX"};
        case 41:
            return {"/shared/kungfu/journal/TD_Q/COINFLEX/", "TD_Q_COINFLEX"};
        case 42:
            return {"/shared/kungfu/journal/TD_Q/COINFLOOR/", "TD_Q_COINFLOOR"};
		default:
			return {"", ""};
	}
	*/
}

inline std::string getLfActionFlagType(char data)
{
	switch(data)
	{
		case '1':
			return "Suspend";
		case '0':
			return "Delete";
		case '3':
			return "Modify";
		case '2':
			return "Active";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfDirectionType(char data)
{
	switch(data)
	{
		case '1':
			return "Sell";
		case '0':
			return "Buy";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfYsOrderStateType(char data)
{
	switch(data)
	{
		case 'A':
			return "YsLeftDeleted";
		case 'C':
			return "YsDeleted";
		case 'B':
			return "YsFail";
		case 'E':
			return "YsDeletedForExpire";
		case 'D':
			return "YsSuppended";
		case 'G':
			return "YsApply";
		case 'F':
			return "YsEffect";
		case '1':
			return "YsAccept";
		case '0':
			return "YsSubmit";
		case '3':
			return "YsExctriggering";
		case '2':
			return "YsTriggering";
		case '5':
			return "YsPartFinished";
		case '4':
			return "YsQueued";
		case '7':
			return "YsCanceling";
		case '6':
			return "YsFinished";
		case '9':
			return "YsCanceled";
		case '8':
			return "YsModifying";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfYsPositionEffectType(char data)
{
	switch(data)
	{
		case 'C':
			return "YsClose";
		case 'T':
			return "YsCloseToday";
		case 'O':
			return "YsOpen";
		case 'N':
			return "YsNon";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfOrderPriceTypeType(char data)
{
	switch(data)
	{
		case '1':
			return "AnyPrice";
		case '3':
			return "BestPrice";
		case '2':
			return "LimitPrice";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfForceCloseReasonType(char data)
{
	switch(data)
	{
		case '1':
			return "LackDeposit";
		case '0':
			return "NotForceClose";
		case '3':
			return "MemberOverPositionLimit";
		case '2':
			return "ClientOverPositionLimit";
		case '5':
			return "Violation";
		case '4':
			return "NotMultiple";
		case '7':
			return "PersonDeliv";
		case '6':
			return "Other";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfOffsetFlagType(char data)
{
	switch(data)
	{
		case 'N':
			return "Non";
		case '1':
			return "Close";
		case '0':
			return "Open";
		case '3':
			return "CloseToday";
		case '2':
			return "ForceClose";
		case '5':
			return "ForceOff";
		case '4':
			return "CloseYesterday";
		case '6':
			return "LocalForceClose";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfContingentConditionType(char data)
{
	switch(data)
	{
		case 'A':
			return "AskPriceGreaterEqualStopPrice";
		case 'C':
			return "AskPriceLesserEqualStopPrice";
		case 'B':
			return "AskPriceLesserThanStopPrice";
		case 'E':
			return "BidPriceGreaterEqualStopPrice";
		case 'D':
			return "BidPriceGreaterThanStopPrice";
		case 'F':
			return "BidPriceLesserThanStopPrice";
		case 'H':
			return "BidPriceLesserEqualStopPrice";
		case '1':
			return "Immediately";
		case '3':
			return "TouchProfit";
		case '2':
			return "Touch";
		case '5':
			return "LastPriceGreaterThanStopPrice";
		case '4':
			return "ParkedOrder";
		case '7':
			return "LastPriceLesserThanStopPrice";
		case '6':
			return "LastPriceGreaterEqualStopPrice";
		case '9':
			return "AskPriceGreaterThanStopPrice";
		case '8':
			return "LastPriceLesserEqualStopPrice";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfVolumeConditionType(char data)
{
	switch(data)
	{
		case '1':
			return "AV";
		case '3':
			return "CV";
		case '2':
			return "MV";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfHedgeFlagType(char data)
{
	switch(data)
	{
		case '1':
			return "Speculation";
		case '9':
			return "AllValue";
		case '3':
			return "Hedge";
		case '2':
			return "Argitrage";
		case '4':
			return "MarketMaker";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfTimeConditionType(char data)
{
	switch(data)
	{
		case 'A':
			return "FAK";
		case 'O':
			return "FOK";
		case '1':
			return "IOC";
		case '3':
			return "GFD";
		case '2':
			return "GFS";
		case '5':
			return "GTC";
		case '4':
			return "GTD";
		case '6':
			return "GFA";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfYsSideTypeType(char data)
{
	switch(data)
	{
		case 'A':
			return "YsAll";
		case 'S':
			return "YsSell";
		case 'B':
			return "YsBuy";
		case 'N':
			return "YsNon";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfYsTimeConditionType(char data)
{
	switch(data)
	{
		case '1':
			return "YsGTC";
		case '0':
			return "YsGFD";
		case '3':
			return "YsFAK";
		case '2':
			return "YsGTD";
		case '4':
			return "YsFOK";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfPositionDateType(char data)
{
	switch(data)
	{
		case '1':
			return "Today";
		case '3':
			return "Both";
		case '2':
			return "History";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfYsHedgeFlagType(char data)
{
	switch(data)
	{
		case 'N':
			return "YsNon";
		case 'B':
			return "YsB";
		case 'T':
			return "YsT";
		case 'L':
			return "YsL";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfPosiDirectionType(char data)
{
	switch(data)
	{
		case '1':
			return "Net";
		case '3':
			return "Short";
		case '2':
			return "Long";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfOrderStatusType(char data)
{
	switch(data)
	{
		case 'a':
			return "Unknown";
		case 'c':
			return "Touched";
		case 'b':
			return "NotTouched";
		case 'd':
			return "Error";
		case 'i':
			return "OrderInserted";
		case 'j':
			return "OrderAccepted";
		case '1':
			return "PartTradedQueueing";
		case '0':
			return "AllTraded";
		case '3':
			return "NoTradeQueueing";
		case '2':
			return "PartTradedNotQueueing";
		case '5':
			return "Canceled";
		case '4':
			return "NoTradeNotQueueing";
		case '6':
			return "AcceptedNoReply";
		case 'k':
			return "PendingCancel";
		default:
			return "UnExpected!";
	};
}

inline std::string getLfYsOrderTypeType(char data)
{
	switch(data)
	{
		case '1':
			return "YsMarket";
		case '2':
			return "YsLimit";
		default:
			return "UnExpected!";
	};
}
#endif

